# Generated by Django 4.1.7 on 2023-03-12 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mappack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('ecu', models.CharField(max_length=255)),
                ('softwareversion', models.CharField(max_length=255)),
            ],
        ),
    ]
